### ISSUE TITLE
Doubt about the socks proxy5 

### ISSUE THREAD

**Issue by F4kda7** [nil0x42/phpsploit#114]
Hello,

It's possible with phpsploit and the socks proxy route the traffic to another server 

The goal is:

If i route the traffic of the server1 to the second server2

then i can run selected applications using the traffic from the server1 
(like Proxychains)

Btw what kind of encryption has the traffic?

Thank you

**Comment by nil0x42** [comment]
Hi, i'm not sure i understood your question.

So you want to use a VPS or any other machine as a socks5 proxy, right ?

Phpsploit has no encryption. It only compresses (zlib) and encodes (b64) payloads, then splits them into HTTP headers.
So you could code a wireshark dissector to analyse what's happening.
Therefore, as standard http logging tools do not keep a copy of every http header, the payloads will not be logged in most cases.

If i didn't answer your question correctly, let me know :)

**Comment by F4kda7** [comment]
Hi,

Thanks for your reply 

I'm looking for the possibility to use an intermediary host like a proxy server (vps or another host i own)

So i was wondering if phpsploit could be useful in this case (or another application/program)

It could be a nice feature if the traffic was encrypted 

i will use it but only in my vms to practice pentesting but I would like it to be as realistic as possible, on the other hand

do you know any program that meets these characteristics? (minimalistic, with cli, traffic encrypted)

Like tunna or Xtunnel it could be a good option (?)

everything can always be improved :) 

Unfortunately my coding skills could be better..

Thank you so much for your time 

Happy weekend

**Comment by nil0x42** [comment]
Hi! The problem with encrypting traffic is that at some point, your key is disclosed.
If you use you tunnel to find a vuln to put a phpsploit backdoor, at that specific moment the backdoor's content (which contains the key) will be dislosed in the tunnel, so a forensic guy will be able to decode anywas.

Of course there is the case where your attack vector involves another route, but at any moment the key is disclosed anyway (unless the target site is over https).

Another issue that always preevented me from implementing encryption, is the fact that the physical payload would have to be a lot bigger (from now the payload is less than 50 chars, and does not alter the page functionality, so it's easy to hide in an existing remote php file or loaded library, in order to remains stealth).

What i absolutly to avoid is a self contained malicious code like c99.php which is too noisy IMHO.

If you have a suggestion to implement encryption without making the payload code too large, i'll be happy to hear it.

For your tunnel, a simple ssh tunnel will do the work

**Comment by F4kda7** [comment]
Hi ^^

"If you use you tunnel to find a vuln to put a phpsploit backdoor, at that specific moment the backdoor's content (which contains the key) will be dislosed in the tunnel, so a forensic guy will be able to decode anywas"

 this is a interesting fact and I didn't expect it..
 then in this first case it's applicable on this kind of implemented transports ? for example: rsa, aes, obfs3,scramblesuit..
 i should read more about the application layer encryption XD
 
  "Of course there is the case where your attack vector involves another route, but at any moment the key is disclosed anyway (unless the target site is over https)"
  
this makes sense because the encryption based on the security of SSL / TLS texts creates an encrypted channel (whose level of encryption depends on the remote server and the browser used by the client)

and about the encryption without making the encryption payload too big someone recommends me https://nacl.cr.yp.to/ ( but the project is dead , so i preffer personally this fork https://github.com/jedisct1/libsodium)

for php there's this fork -> https://github.com/jedisct1/libsodium-php#encrypt-a-single-message-using-a-secret-key-and-hide-its-length

more info ->  https://paragonie.com/blog/2015/09/how-to-safely-implement-cryptography-in-any-application

thank you for your time then i'll use a tunnel ssh 

cheers 

PS: i think i can close this issue 

thax =)
