### ISSUE TITLE
phpsploit is not working properly

### ISSUE THREAD

**Issue by an0n7m** [nil0x42/phpsploit#128]
I tried to run phpsploit on my Ubuntu server after my parrot Linux ran successfully, but an error occurred
![图片](https://user-images.githubusercontent.com/33892623/69407309-30242f80-0d3f-11ea-8dc5-b84c05a440b5.png)
I don't know why it happened，please help me

**Comment by nil0x42** [comment]
Hi ! This is a special case i did not address indeed. Thank you for the bug report.
It happens when using phpsploit in a system with no web browser installed.
Anyway, here is the fix: https://github.com/nil0x42/phpsploit/pull/129

Just pull, checkout to `wip` branch and tell me if it fixes your issue.
Anyway i'm gonna merge it soon into master

**Comment by nil0x42** [comment]
Now merged to master.
`git pull` the project and it shoudl work
