### ISSUE TITLE
Python help

### ISSUE THREAD

**Issue by jackzett** [nil0x42/phpsploit#22]
"root@kali:~/phpsploit# python3 phpsploit
Traceback (most recent call last):
  File "/root/phpsploit/deps/__init__.py", line 29, in <module>
    __import__(module)
ImportError: No module named shutil_update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/phpsploit/deps/__init__.py", line 36, in <module>
    imp.load_package(module, abspath)
  File "/root/phpsploit/deps/./shutil_update/__init__.py", line 14, in <module>
    needs('which', 'get_terminal_size')
  File "/root/phpsploit/deps/./shutil_update/__init__.py", line 10, in needs
    module = getattr(__import__('shutil_new'), attr)
ImportError: No module named shutil_new

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phpsploit", line 16, in <module>
    import src  # spread phpsploit sources
  File "/root/phpsploit/src/__init__.py", line 15, in <module>
    import deps
  File "/root/phpsploit/deps/__init__.py", line 38, in <module>
    except (ImportError, FileNotFoundError):
NameError: name 'FileNotFoundError' is not defined"

I seem to have that error message when running it, this may be my own fault but anyways...
Any suggestions?

**Comment by nil0x42** [comment]
Thanks for the feedback.
I took a look at your issue, and discovered that the framework had some incompatibilities with
python < 3.3.

Indeed, the exception you encountered had been thrown because i was using standard exceptions
from PEP-3151 ( https://docs.python.org/3.3/whatsnew/3.3.html#pep-3151 ).

I also had another problem with shutil, etc..

I fixed issues i found, testing it with python 3.2.3, therefore, other problems may be hidden in the framework, using a python version < 3.3.

Currently, my fixes are available in the following branch:
https://github.com/nil0x42/phpsploit/tree/issue_22_PEP3151

Please, can you try this branch, in order to confirm that everything is fine for you before i merge it ?
Also, i'd like to know what exactly is the version of python you are using.

Have fun with phpsploit :+1:

**Comment by nil0x42** [comment]
Just merged changes into `master`: 9fe6660ad9ef7c4a160615dfd3905d19811d0cf1

**Comment by nil0x42** [comment]
fixed by 965657558e5b55c24f8f07c6ac6241ed0750dfa
